export default [
    {
        id:'1',
        title:'기본',
        categories:0,
        name:'cloth1',
        image:require('@/assets/character/cloth1.png'),
        own:'true',
        price:0,
    },
    {
        id:'2',
        title:'가죽자켓',
        categories:0,
        name:'cloth2',
        image:require('@/assets/character/cloth2.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'3',
        title:'바다속 배경',
        categories:2,
        name:'background1',
        image: require('@/assets/character/background1.png'),
        own:'false',
        price: 1000,
    },
    {
        id:'4',
        title:'로멘틱 하늘',
        categories:2,
        name:'background2',
        image:require('@/assets/character/background2.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'5',
        title:'공장지대',
        categories:2,
        name:'background3',
        image:require('@/assets/character/background3.png'),
        own:'false',
        price: 1000,
    },
    {
        id:'6',
        title:'나는야 슈퍼맨',
        categories:0,
        name:'cloth3',
        image:require('@/assets/character/cloth3.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'7',
        title:'슈퍼맨 머리',
        categories:1,
        name:'hair1',
        image:require('@/assets/character/hair1.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'8',
        title:'멋쟁이 안경',
        categories:1,
        name:'hair2',
        image:require('@/assets/character/hair2.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'9',
        title:'고양이귀',
        categories:1,
        name:'hair3',
        image:require('@/assets/character/hair3.png'),
        own:'false',
        price: 1000,

    },
    {
        id:'10',
        title:'스미티 워벤 재거 맨 잰슨의 모자',
        categories:1,
        name:'hair4',
        image:require('@/assets/character/hair4.png'),
        own:'false',
        price: 1000,

    },    
    {
        id:'11',
        title:'직원용 유니폼',
        categories:1,
        name:'hair5',
        image:require('@/assets/character/hair5.png'),
        own:'false',
        price: 1000,
    },
    {
        id:'12',
        title:'누군가의 옷',
        categories:0,
        name:'cloth4',
        image:require('@/assets/character/cloth4.png'),
        own:'false',
        price: 1000,
    },
    {
        id:'13',
        title:'17세기 국자',
        categories:3,
        name:'deco1',
        image:require('@/assets/character/deco1.png'),
        own:'false',
        price: 1000,
    },
    {
        id:'14',
        title:'게살버거',
        categories:3,
        name:'deco2',
        image:require('@/assets/character/deco2.png'),
        own:'false',
        price: 1000,
    },
]